language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "x4XK24ec1UTxEgriPWz/UEiHFsxXt5aQBqJspdHisp0FX9v6czPY+EHb+rFr48WBgcluZcGL6gKUDcE52cRzN7il6aXSIpXK2fV5hRac9IC9Az+OVMsRd1/6ywFHofE2VvDzvujBjeOhVPOwCQaMgy6LjlWq0poH+BDvFf1kLBg="

addons:
  coverity_scan:
    project:
      name: "centaurean/cputime"
      description: "Build submitted via Travis CI"
    notification_email: gpnuma@centaurean.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan

script:
  - cd build
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0.alpha4/premake-5.0.0.alpha4-linux.tar.gz
  - tar zxvf premake-5.0.0.alpha4-linux.tar.gz
  - ./premake5 gmake
  - make clean
  - make