version: 1.0.{build}

install:
  - cmd: cd build
  - ps: wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip -OutFile premake5.zip
  - cmd: 7z x premake5.zip
  - cmd: del premake5.zip

build_script:
  - cmd: premake5 vs2017
  - cmd: msbuild CPUTime.sln
